version: "3.9"
services:
  redis-server:
    image: "redis:alpine"
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"
    expose:
      - 6379
  server:
    depends_on:
      - redis-server
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "3000:3000"
    volumes:
      - .:/code
      - /code/node_modules
    expose:
      - 3000
